### ISSUE TITLE
AudioSample.mod segfaults

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/bcc#426]
```
Thread 1 "GenusPrime.debu" received signal SIGSEGV, Segmentation fault.
0x00007ffff69f9532 in free () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff69f9532 in free () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00000000007c6cbd in _brl_audiosample_TAudioSample_Delete (
    o=0x7fffdf7e04e0)
    at /BlitzMaxNG/mod/brl.mod/audiosample.mod/.bmx/audiosample.bmx.debug.linux.x64.c:111
#2  0x000000000095bbde in GC_invoke_finalizers ()
    at /BlitzMaxNG/mod/brl.mod/blitz.mod/bdwgc/finalize.c:1281
#3  0x000000000095bddc in GC_notify_or_invoke_finalizers ()
    at /BlitzMaxNG/mod/brl.mod/blitz.mod/bdwgc/finalize.c:1360
#4  0x000000000095d137 in GC_generic_malloc (lb=32, k=1)
    at /BlitzMaxNG/mod/brl.mod/blitz.mod/bdwgc/malloc.c:247
#5  0x000000000095d962 in GC_malloc_kind_global (k=1, lb=<optimized out>)
    at /BlitzMaxNG/mod/brl.mod/blitz.mod/bdwgc/malloc.c:327
#6  GC_malloc_kind (k=1, lb=<optimized out>)
    at /BlitzMaxNG/mod/brl.mod/blitz.mod/bdwgc/malloc.c:333
#7  GC_malloc (lb=<optimized out>)
    at /BlitzMaxNG/mod/brl.mod/blitz.mod/bdwgc/malloc.c:346
```
(interesting the name is "GenusPrime.debu" - without G at the end).

This happens on brl.mod/pub.mod _before_ the new GC-stuff was implemented.

**Comment by GWRon** [comment]
If you want I could setup a little sample project using the code - so you could check on a live patient.

**Comment by woollybah** [comment]
I have a fix, but it fundamentally changes the cast expr type check for everything... so I need to do some more testing first...

**Comment by GWRon** [comment]
Ok.
If it was a fundamental change I wonder why nothing else needed a fix in that regards till now.

**Comment by woollybah** [comment]
Seems fine. You shouldn't need that NG-specifc code change now, as it should correctly cast to Byte Ptr before attempting to do the pointer addition.
